{
    "sharding" : false,
    "server_name" : "brubeck_huginn",
    "dumpfile" : "/var/log/brubeck.dump",
    "capacity" : 2000,
    "expire" : 7,
    "backends" :
    [
	{
	    "type" : "carbon",
	    "address" : "muninn.local",
	    "port" : 2004,
	    "frequency" : 10,
	    "pickle" : true
	}
    ],
    "samplers" :
    [
	{
	    "type" : "statsd",
	    "address" : "0.0.0.0",
	    "port" : 9125,
	    "workers" : 8,
	    "multisock" : true,
	    "multimsg" : 0
	}
    ]
}
